### ISSUE TITLE
Parameters with "-" dont work

### ISSUE THREAD

**Issue by LocutusOfPenguin** [albfan/bash-ini-parser#14]
Hi,
if my ini file has items like this:
beep-some-level = 3
enable-console = True

It crushes (cause "-" not valid for vars on bash).
I would propose to rename them on READ from "-" to "_", and on WRITE back to "-".

Thats similar to pythons configargparse (and the reason, we have them)

**Comment by albfan** [comment]
Hmm, What is the expected behaviour for:

```
beep-some-level = 3
beep_some_level = 5
```

I think first step is warn about unsupported characters on keys
Then maybe add a ENV var to allow character replaces

Do you think you can provide a failed test use case?

**Comment by LocutusOfPenguin** [comment]
Good point - but i make myself easy :-) This case wont happen to me.
So, i can live with all - i hope to not give too much work to you!

Ok, perhaps best to have a parameter to allow this substitution,
even the mentioned configargparse seems to have nothing to change this "-_" exchange behavior :-(

**Comment by albfan** [comment]
Although I totally discouraged to use this approach -better use convention over configuration. Here convention is not to use '-' chars for keys- You can fix your issue (at least for read by now) in https://github.com/albfan/bash-ini-parser/tree/wip/invalid-chars. See [README Hacking zone](https://github.com/albfan/bash-ini-parser/tree/wip/invalid-chars#hacking-zone) and the specific test [t0005-invalid-chars.sh](https://github.com/albfan/bash-ini-parser/tree/wip/invalid-chars/t/t0005-invalid-chars.sh)

**Comment by LocutusOfPenguin** [comment]
Hi,
as i said before, i agree this is prob. not so good idea - but yr version working.
I solved my problems with a python wrapper of whiptail.
This also allows me to keep comments. Thanks.
