### ISSUE TITLE
Please add LICENSE to authorize us to use

### ISSUE THREAD

**Issue by CHN-STUDENT** [albfan/bash-ini-parser#15]
Hi,Glad to see you again, And i want to hope you add LICENSE to authorize us to use. My friend and I use your `bash-ini-parser` for our shell script [WebServerAutoBackup](https://github.com/CHN-STUDENT/WebServerAutoBackup) ,it is a auto backup script for backing up Web directory + MySQL, And we integrate your script in our backup script [backup.sh](https://github.com/CHN-STUDENT/WebServerAutoBackup/blob/master/backup.sh "backup.sh") to parse the user config file [config.ini](https://github.com/CHN-STUDENT/WebServerAutoBackup/blob/master/config.ini "config.ini"). So we hope you add LICENSE to authorize us to use.

Our project is free,open source,and easy to user use,we are students who are enjoying coding and sharing it with other to improve our code level. And we think more and more people use our project,Could you authorize us to use?

By the way,we hope our project in your project README as a demo, we think it is good for show our project and share us code with other.

**Comment by albfan** [comment]
Done! Close this if you find all your request are fullfilled

**Comment by CHN-STUDENT** [comment]
@albfan Thank you! But i have a question, should we need to change our project LICENSE to GPL LICENSE follow you? Now we are using MIT LICENSE.

**Comment by albfan** [comment]
Nice you take care of this, enjoy bash-ini-parser!
