### ISSUE TITLE
Allow multiple files

### ISSUE THREAD

**Issue by rockandska** [albfan/bash-ini-parser#37]
Hi,

Would be great to allow sourcing from multiple files to be able to do something like

```
cfg_parser /etc/mysql/my.cnf /etc/mysql/conf.d/*.cnf
```

Regards,

**Comment by albfan** [comment]
See you can call `cfg_parser` multiple times. It reads a file per call:

https://github.com/albfan/bash-ini-parser/blob/master/bash-ini-parser#L25

So you can get that you want doing:

```
for f in  /etc/mysql/my.cnf /etc/mysql/conf.d/*.cnf
do
   cfg_parser "$f"
done
```
See matching sections and properties will override, so in the typical global -> user -> project fallback, you just need to set the correct order of files to read.

Let me know if there's any pitfall on that, and I can reopen this issue.
